name: Tests
on: [push, pull_request]

jobs:
   tests:
      name: PHP ${{ matrix.php }} Latest
      runs-on: ubuntu-latest
      strategy:
         matrix:
            php: [ '8.1', '8.2', '8.3', '8.4' ]
         fail-fast: false

      steps:
         -  name: Checkout code
            uses: actions/checkout@v2

         -  name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
               php-version: ${{ matrix.php }}
               coverage: xdebug
         -  name: Get Composer Cache Directory
            id: composer-cache
            run: echo "::set-output name=dir::$(composer config cache-files-dir)"

         -  name: Cache dependencies
            uses: actions/cache@v3
            with:
               path: ${{ steps.composer-cache.outputs.dir }}
               key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
               restore-keys: ${{ runner.os }}-composer-

         -  name: Install Dependencies
            run: composer update --prefer-dist --no-interaction --optimize-autoloader --no-progress

         -  name: Execute tests
            run: composer test
